### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by procrastinatio**
* Embryonic documentation
* `make` aws s3 bucket notification
* `make` invoke

### CODE REVIEW

**Comment by gjn** [comment]
+1 for this. Thanks alot.

Under which account is this currently running? (I don't see the aws lambda function in aws-admin).

Also, how long does the execution take and how much RAM do you allocate?

**Comment by procrastinatio** [comment]
@gjn Configuration is done via the main `project.json` in project's root or in function's dir.

For now, you have to export `AWS_PROFILE` and `AWS_REGION`

I still have to create a script checking/creating custom role and policy, if deploying to a new account. IAM's role and policy management is always very weak in all these frameworks (i.e. allow '*' on '*' resources, yukes!))

**Comment by procrastinatio** [comment]
It is now in the '2568********' account (a test one), on the bucket 'dummy-lambda-test', which is used by @loicgasser' s demos

**Comment by gjn** [comment]
ok. That's good for now.

Any info on the execution time per call ? Rough estimate is fine.

**Comment by procrastinatio** [comment]
Billed values (first few requests are notably lengthier, up to timeout value of 15s)
JPEG: something between 100-400ms (only striping some EXIF fields)
PNG: about 200-800 ms (multipass)

Max memory used <40MB

**Pull request merged**
